package com.bigcustard.silverbars.model;

public class Order {

    private final String userId;
    private final int quantityInGrams; // Quantities held in grams to avoid rounding issues.
    private final Bid bid;


    public Order(String userId, int quantityInGrams, Bid bid) {

        if(bid == null) {
            throw new IllegalArgumentException("Bid must not be null");
        }

        this.userId = userId;
        this.quantityInGrams = quantityInGrams;
        this.bid = bid;
    }

    public Order(String userId, int quantiy, OrderType buyOrSell, int pencePerKg) {

        this(userId, quantiy, new Bid(buyOrSell, pencePerKg));
    }

    public String getUserId() {

        return userId;
    }

    public int getQuantityInGrams() {

        return quantityInGrams;
    }

    public Bid getBid() {

        return bid;
    }

    @Override
    public boolean equals(Object o) {

        // Generated by IntelliJ
        if (this == o) return true;
        if (!(o instanceof Order)) return false;

        Order order = (Order) o;

        return quantityInGrams == order.quantityInGrams && userId.equals(order.userId) && bid.equals(order.bid);
    }

    @Override
    public int hashCode() {

        // Generated by IntelliJ
        int result = userId.hashCode();
        result = 31 * result + quantityInGrams;
        result = 31 * result + bid.hashCode();
        return result;
    }
}
